FROM rust:1.77.2

RUN apt-get update && apt-get install -y \
    clang \
    libasound2-dev \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

# Install Clippy and rustfmt
RUN rustup component add clippy rustfmt
