---
name: Ansible

"on":
  push:
    branches:
      - main
    paths:
      - "ansible/**"
  pull_request:
    paths:
      - "ansible/**"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/ansible-lint.yml
    with:
      path: "ansible"
