---
name: Ansible

"on":
  workflow_call:
    inputs:
      path:
        default: "/"
        required: false
        type: string

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.16.0
        with:
          path: "${{ inputs.path }}"
