---
name: Docker

"on":
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - Dockerfile.rust

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image name from Dockerfile name
        id: name
        run: |
          image_name=$(echo ${{ matrix.dockerfile }} | cut -d '.' -f 2)
          echo "image_name=$image_name" >> $GITHUB_OUTPUT
          echo "$image_name"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.name.outputs.image_name }}:latest
