---
name: Markdown

"on":
  pull_request:

jobs:
  filter:
    name: Changed files
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.changed-files-specific.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: "*.md"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done

  lint:
    name: Lint

    needs: filter

    uses: ./.github/workflows/markdown-lint.yml
    if: ${{ needs.filter.outputs.changed == 'true' }}

  style:
    name: Style

    needs: filter

    uses: ./.github/workflows/markdown-style.yml
    if: ${{ needs.filter.outputs.changed == 'true' }}
