---
name: Markdown

"on":
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.md"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/markdown-lint.yml

  style:
    name: Style
    uses: ./.github/workflows/markdown-style.yml
