---
name: Rust

"on":
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSL headers
        run: sudo apt-get install libssl-dev

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.2.0

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
