---
name: Rust

"on":
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jdno/rust:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Rustfmt
        run: cargo fmt --all -- --check
