---
name: Rust

"on":
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jdno/rust:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.3.0

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
