---
name: Shell

"on":
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.sh"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/shell-lint.yml

  style:
    name: Style
    uses: ./.github/workflows/shell-style.yml
