---
name: Terraform

"on":
  workflow_call:
    inputs:
      path:
        default: "."
        required: false
        type: string

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.2.9

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run terraform fmt
        working-directory: ${{ inputs.path }}
        run: terraform fmt -check -recursive .
