---
name: Terraform

"on":
  workflow_call:
    inputs:
      path:
        default: "."
        required: false
        type: string

jobs:
  security:
    name: Audit security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ github.token }}
          working_directory: ${{ inputs.path }}
