---
name: YAML

"on":
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/yaml-lint.yml

  style:
    name: Style
    uses: ./.github/workflows/yaml-style.yml
